fibonacci:
	gcc -g -o fibonacci fibonacci.c

pascal:
	gcc -g -o pascal pascal.c

array_sum:
	gcc -g -o array_sum array_sum.c

rotate_vector:
	gcc -g -o rotate_vector rotate_vector.c

clean:
	rm -f fibonacci pascal array_sum rotate_vector
